volumes:
  postgres_moldova:
  postgres_romania:
  postgres_bulgaria:
  postgres_dwh:

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: delivery_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d
  
  db_moldova:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_moldova:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d

  db_romania:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - postgres_romania:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d

  db_bulgaria:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - postgres_bulgaria:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d

  dwh:
    image: postgres:15
    container_name: postgres_dwh
    environment:
      POSTGRES_DB: dwh_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5436:5432"
    volumes:
      - postgres_dwh:/var/lib/postgresql/data
      - ./docker/init-dwh:/docker-entrypoint-initdb.d